HORIZONTAL_OFFSET = .02;
VERTICAL_OFFSET = .075;
SMALL_WIDTH = .25;
SMALL_HEIGHT = .4;
BIG_WIDTH = .4;
BIG_HEIGHT = 2*SMALL_HEIGHT + VERTICAL_OFFSET;
subplot('Position', [HORIZONTAL_OFFSET, 2*VERTICAL_OFFSET + SMALL_HEIGHT, SMALL_WIDTH, SMALL_HEIGHT])

subplot('Position', [2*HORIZONTAL_OFFSET + SMALL_WIDTH, 2*VERTICAL_OFFSET + SMALL_HEIGHT, SMALL_WIDTH, SMALL_HEIGHT])

subplot('Position', [HORIZONTAL_OFFSET, VERTICAL_OFFSET, SMALL_WIDTH, SMALL_HEIGHT])

subplot('Position', [2*HORIZONTAL_OFFSET + SMALL_WIDTH, VERTICAL_OFFSET, SMALL_WIDTH, SMALL_HEIGHT])

subplot('Position', [3*HORIZONTAL_OFFSET + 2*SMALL_WIDTH, VERTICAL_OFFSET, BIG_WIDTH, BIG_HEIGHT])



